### ISSUE TITLE
ImageSharp.Web.Providers.AWS.csproj Missing

### ISSUE THREAD

**Issue by chandrainspire** [andyfelton-equatedigital/Umbraco.StorageProviders.AWSS3#1]
We see the project ImageSharp.Web.Providers.AWS.csproj is missing, can you please provide it. Many Thanks.

**Comment by andyfelton2** [comment]
Hi,

You can get that file from ImageSharp.Web.

Thanks
Andy

**Comment by chandrainspire** [comment]
May I request to upload that project to GitHub as well please, that will make your solution complete.

**Comment by andyfelton-equatedigital** [comment]
Hi,

As this version is for Umbraco 9 which needs so many workarounds to get it to work (As ImageSharp.Web 2.0 isn't used) I'll be moving this to Umbraco 10 as soon as I get a chance. This will the resolve all the issues. 

Sorry I won't upload the files from ImageSharp.Web you need to get these from https://github.com/SixLabors/ImageSharp.Web.

Thanks
Andy
